apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-example
    namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: frontend-dev.rdevopsb83.online
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80