apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if($scheme = http) {
        return 301 https://$host$request_uri;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: frontend-dev1.saitejasroboshop.store
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80